#include "Delay.h"
Delay::Delay()
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Delay::Initialize() {
	timer.Start();
}
// Called repeatedly when this Command is scheduled to run
void Delay::Execute() {
	
}
// Make this return true when this Comma and no longer needs to run execute()
bool Delay::IsFinished() {
	return timer.HasPeriodPassed(0.0 /*Robot::autoPref->GetDouble("DelayShooting", 0.0)*/);
}
// Called once after isFinished returns true
void Delay::End() {
	timer.Stop();
	timer.Reset();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Delay::Interrupted() {
}
