#include "RunShooter.h"
RunShooter::RunShooter() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void RunShooter::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void RunShooter::Execute() {
	Robot::shooter->shooter1->Set(1.0);
	Robot::shooter->shooter2->Set(1.0);
}
// Make this return true when this Comma and no longer needs to run execute()
bool RunShooter::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void RunShooter::End() {
	Robot::shooter->shooter1->Set(0.0);
	Robot::shooter->shooter2->Set(0.0);
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RunShooter::Interrupted() {
}
