// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ARM_H
#define ARM_H
#include "Commands/Subsystem.h"
#include "CANJaguar.h"
#include "PIDController.h"
#include "Encoder.h"
/**
 *
 *
 * @author ExampleAuthor
 */
#include "../DoubleMotor.h"
class Arm: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* arm1;
	CANJaguar* arm2;
	Encoder* armEncoder;
	PIDController* controller;
	DoubleMotor* arm;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Arm();
	void InitDefaultCommand();

};
#endif
